function copy(lang, tr, en) {
  return lang === "en" ? en : tr;
}

function escapeHtml(s) {
  return String(s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function emailShell(lang, title, bodyHtml) {
  const slogan = copy(lang, "Fişi çek, gerisini Saklio halletsin.", "Snap the receipt, Saklio does the rest.");
  const footer = copy(lang, "Bu e-posta Saklio tarafından oluşturuldu. Produced by aystech · Kayra Çatalkaya", "This email was generated by Saklio. Produced by aystech · Kayra Çatalkaya");
  return `<!DOCTYPE html>
<html lang="${lang}">
<head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body style="margin:0;padding:0;background:#F8F7F2;">
  <div style="background:#F8F7F2;padding:32px 16px;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;">
    <div style="max-width:520px;margin:0 auto;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #EAE8DF;box-shadow:0 12px 40px rgba(14,36,26,0.06);">
      <div style="background:linear-gradient(135deg,#8FCFAE,#5B9F7D);padding:28px 32px;">
        <div style="color:#0E241A;font-size:22px;font-weight:700;letter-spacing:2.4px;">saklio</div>
        <div style="color:#0E241A;opacity:.78;font-size:13px;margin-top:6px;">${escapeHtml(slogan)}</div>
      </div>
      <div style="padding:28px 32px;color:#202522;">
        <h2 style="margin:0 0 12px;font-size:22px;line-height:1.3;color:#0E241A;">${escapeHtml(title)}</h2>
        ${bodyHtml}
      </div>
      <div style="padding:16px 32px;color:#757D78;font-size:12px;border-top:1px solid #EAE8DF;">${escapeHtml(footer)}</div>
    </div>
  </div>
</body>
</html>`;
}

function welcomeEmailHtml(lang, name) {
  const title = copy(lang, "Saklio’ya hoş geldin 👋", "Welcome to Saklio 👋");
  const hello = name
    ? copy(lang, `Merhaba ${escapeHtml(name)},`, `Hi ${escapeHtml(name)},`)
    : copy(lang, "Merhaba,", "Hi,");
  const body = copy(
    lang,
    "Fişlerini, iade sürelerini ve garantilerini tek yerde tutacağız. İlk fişini tarayarak başlayabilirsin.",
    "We’ll keep your receipts, return windows and warranties in one place. Start by scanning your first receipt."
  );
  return emailShell(lang, title, `<p style="margin:0 0 12px;color:#3C4742;line-height:22px;">${hello}</p><p style="margin:0;color:#757D78;line-height:22px;">${escapeHtml(body)}</p>`);
}

function deleteCodeEmailHtml(lang, code) {
  const title = copy(lang, "Veri silme onayı", "Confirm data deletion");
  const body = copy(
    lang,
    "Hesabındaki ürün ve belge verilerini silmek için aşağıdaki kodu kullan. Kod 15 dakika geçerlidir.",
    "Use the code below to delete product and document data from your account. The code expires in 15 minutes."
  );
  const label = copy(lang, "Onay kodun", "Your confirmation code");
  return emailShell(
    lang,
    title,
    `<p style="margin:0 0 18px;color:#757D78;line-height:22px;">${escapeHtml(body)}</p>
     <div style="background:#F8F7F2;border:1px solid #EAE8DF;border-radius:16px;padding:18px;text-align:center;">
       <div style="font-size:12px;letter-spacing:1px;text-transform:uppercase;color:#757D78;">${escapeHtml(label)}</div>
       <div style="font-size:32px;letter-spacing:8px;font-weight:700;color:#0E241A;margin-top:8px;">${escapeHtml(code)}</div>
     </div>`
  );
}

function reminderEmailHtml(lang, kind, productName, days) {
  const title = kind === "return"
    ? copy(lang, "İade süresi yaklaşıyor", "Return window ending")
    : copy(lang, "Garanti bitiyor", "Warranty ending");
  const left = copy(lang, `${days} gün kaldı`, `${days} days left`);
  return emailShell(
    lang,
    title,
    `<p style="margin:0 0 8px;color:#0E241A;font-size:18px;font-weight:600;">${escapeHtml(productName)}</p>
     <p style="margin:0;color:#757D78;line-height:22px;">${escapeHtml(left)}</p>`
  );
}

function exportReadyHtml(lang, counts) {
  const title = copy(lang, "Verilerin hazır", "Your data is ready");
  const body = copy(
    lang,
    `Ürünlerin ve belgelerinin özeti ektedir. ${counts.products || 0} ürün, ${counts.documents || 0} belge.`,
    `A summary of your products and documents is attached. ${counts.products || 0} products, ${counts.documents || 0} documents.`
  );
  return emailShell(lang, title, `<p style="margin:0;color:#757D78;line-height:22px;">${escapeHtml(body)}</p>`);
}

function bannedHtml(lang) {
  const title = copy(lang, "Hesabın askıya alındı", "Your account was suspended");
  const body = copy(
    lang,
    "Saklio hesabın yönetici tarafından askıya alındı. Yardım için saklio@aystech.com.tr adresine yaz.",
    "Your Saklio account was suspended by an administrator. Contact saklio@aystech.com.tr if you need help."
  );
  return emailShell(lang, title, `<p style="margin:0;color:#757D78;line-height:22px;">${escapeHtml(body)}</p>`);
}

module.exports = { emailShell, welcomeEmailHtml, deleteCodeEmailHtml, reminderEmailHtml, exportReadyHtml, bannedHtml };

