export type MailLang = "tr" | "en";

const COPY = {
  slogan: { tr: "Fişi çek, gerisini Saklio halletsin.", en: "Snap the receipt, Saklio does the rest." },
  welcomeT: { tr: "Saklio’ya hoş geldin 👋", en: "Welcome to Saklio 👋" },
  welcomeB: {
    tr: "Fişlerini, iade sürelerini ve garantilerini tek yerde tutacağız. İlk fişini tarayarak başlayabilirsin.",
    en: "We’ll keep your receipts, return windows and warranties in one place. Start by scanning your first receipt.",
  },
  exportT: { tr: "Verilerin hazır", en: "Your data is ready" },
  exportB: {
    tr: "Aşağıda ürünlerin ve belgelerinin özeti var. JSON kopyasını da bu raporla birlikte indirdin.",
    en: "Here’s a summary of your products and documents. You also downloaded a JSON copy with this report.",
  },
  deleteCodeT: { tr: "Veri silme onayı", en: "Confirm data deletion" },
  deleteCodeB: {
    tr: "Hesabındaki ürün ve belge verilerini silmek için aşağıdaki kodu kullan. Kod 15 dakika geçerlidir.",
    en: "Use the code below to delete product and document data from your account. The code expires in 15 minutes.",
  },
  deletedT: { tr: "Verilerin silindi", en: "Your data was deleted" },
  deletedB: {
    tr: "Tüm ürün ve belge verilerin silindi. Hesabın aktif kalmaya devam ediyor.",
    en: "All product and document data was deleted. Your account remains active.",
  },
  returnT: { tr: "İade süresi yaklaşıyor", en: "Return window ending" },
  warrantyT: { tr: "Garanti bitiyor", en: "Warranty ending" },
  daysLeft: { tr: "{n} gün kaldı", en: "{n} days left" },
  products: { tr: "Ürünler", en: "Products" },
  documents: { tr: "Belgeler", en: "Documents" },
  merchant: { tr: "Mağaza", en: "Store" },
  price: { tr: "Fiyat", en: "Price" },
  date: { tr: "Tarih", en: "Date" },
  footer: { tr: "Bu e-posta Saklio tarafından oluşturuldu. Produced by aystech · Kayra Çatalkaya", en: "This email was generated by Saklio. Produced by aystech · Kayra Çatalkaya" },
  codeLabel: { tr: "Onay kodun", en: "Your confirmation code" },
  shoppingT: { tr: "Alışveriş listen", en: "Your shopping list" },
  shoppingB: { tr: "Saklio’dan alışveriş listen. İşaretli olanlar alındı.", en: "Your Saklio shopping list. Checked items are already picked up." },
  qty: { tr: "Miktar", en: "Qty" },
  item: { tr: "Ürün", en: "Item" },
  spendT: { tr: "Aylık harcama raporun", en: "Your monthly spending report" },
  spendB: { tr: "Saklio fişlerinden sektörlere göre harcama özeti.", en: "A sector breakdown from your Saklio receipts." },
  spendTotal: { tr: "Toplam", en: "Total" },
  spendSector: { tr: "Sektör", en: "Sector" },
  spendShare: { tr: "Pay", en: "Share" },
  spendTop: { tr: "En çok harcanan", en: "Top sector" },
};

function c(lang: MailLang, key: keyof typeof COPY, params?: Record<string, string | number>) {
  let s = COPY[key][lang];
  if (params) for (const k in params) s = s.replace(`{${k}}`, String(params[k]));
  return s;
}

export function emailShell(lang: MailLang, title: string, bodyHtml: string) {
  const slogan = c(lang, "slogan");
  const footer = c(lang, "footer");
  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(title)}</title>
</head>
<body style="margin:0;padding:0;background:#F8F7F2;">
  <div style="background:#F8F7F2;padding:32px 16px;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;">
    <div style="max-width:520px;margin:0 auto;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #EAE8DF;box-shadow:0 12px 40px rgba(14,36,26,0.06);">
      <div style="background:linear-gradient(135deg,#8FCFAE,#5B9F7D);padding:28px 32px;">
        <div style="color:#0E241A;font-size:22px;font-weight:700;letter-spacing:2.4px;">saklio</div>
        <div style="color:#0E241A;opacity:.78;font-size:13px;margin-top:6px;">${escapeHtml(slogan)}</div>
      </div>
      <div style="padding:28px 32px;color:#202522;">
        <h2 style="margin:0 0 12px;font-size:22px;line-height:1.3;color:#0E241A;">${escapeHtml(title)}</h2>
        ${bodyHtml}
      </div>
      <div style="padding:16px 32px;color:#757D78;font-size:12px;border-top:1px solid #EAE8DF;line-height:18px;">
        ${escapeHtml(footer)}<br/>
        <img src="https://sakliov2.web.app/brand/aystech.png" alt="aystech" width="96" style="margin-top:10px;height:auto;" />
      </div>
    </div>
  </div>
</body>
</html>`;
}

function escapeHtml(s: string) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function welcomeEmailHtml(lang: MailLang, name?: string) {
  const hello = name ? (lang === "en" ? `Hi ${escapeHtml(name)},` : `Merhaba ${escapeHtml(name)},`) : lang === "en" ? "Hi," : "Merhaba,";
  return emailShell(
    lang,
    c(lang, "welcomeT"),
    `<p style="margin:0 0 12px;color:#3C4742;line-height:22px;">${hello}</p>
     <p style="margin:0;color:#757D78;line-height:22px;">${escapeHtml(c(lang, "welcomeB"))}</p>`
  );
}

export function deleteCodeEmailHtml(lang: MailLang, code: string) {
  return emailShell(
    lang,
    c(lang, "deleteCodeT"),
    `<p style="margin:0 0 18px;color:#757D78;line-height:22px;">${escapeHtml(c(lang, "deleteCodeB"))}</p>
     <div style="background:#F8F7F2;border:1px solid #EAE8DF;border-radius:16px;padding:18px;text-align:center;">
       <div style="font-size:12px;letter-spacing:1px;text-transform:uppercase;color:#757D78;">${escapeHtml(c(lang, "codeLabel"))}</div>
       <div style="font-size:32px;letter-spacing:8px;font-weight:700;color:#0E241A;margin-top:8px;">${escapeHtml(code)}</div>
     </div>`
  );
}

export function deletedEmailHtml(lang: MailLang) {
  return emailShell(lang, c(lang, "deletedT"), `<p style="margin:0;color:#757D78;line-height:22px;">${escapeHtml(c(lang, "deletedB"))}</p>`);
}

export function reminderEmailHtml(lang: MailLang, kind: "return" | "warranty", productName: string, days: number) {
  const title = kind === "return" ? c(lang, "returnT") : c(lang, "warrantyT");
  return emailShell(
    lang,
    title,
    `<p style="margin:0 0 8px;color:#0E241A;font-size:18px;font-weight:600;">${escapeHtml(productName)}</p>
     <p style="margin:0;color:#757D78;line-height:22px;">${escapeHtml(c(lang, "daysLeft", { n: days }))}</p>`
  );
}

export function exportReportHtml(lang: MailLang, payload: { user?: any; products?: any[]; documents?: any[] }) {
  const products = payload.products || [];
  const documents = payload.documents || [];
  const rows = products
    .slice(0, 80)
    .map(
      (p) => `<tr>
        <td style="padding:10px 0;border-bottom:1px solid #EAE8DF;color:#202522;">${escapeHtml(p.name || "—")}</td>
        <td style="padding:10px 0;border-bottom:1px solid #EAE8DF;color:#757D78;">${escapeHtml(p.merchant || "—")}</td>
        <td style="padding:10px 0;border-bottom:1px solid #EAE8DF;color:#202522;text-align:right;">${p.price != null ? escapeHtml(String(p.price)) : "—"}</td>
      </tr>`
    )
    .join("");
  return emailShell(
    lang,
    c(lang, "exportT"),
    `<p style="margin:0 0 18px;color:#757D78;line-height:22px;">${escapeHtml(c(lang, "exportB"))}</p>
     <div style="display:flex;gap:10px;margin-bottom:18px;">
       <div style="flex:1;background:#F8F7F2;border-radius:16px;padding:14px;">
         <div style="font-size:12px;color:#757D78;">${escapeHtml(c(lang, "products"))}</div>
         <div style="font-size:22px;font-weight:700;color:#0E241A;">${products.length}</div>
       </div>
       <div style="flex:1;background:#F8F7F2;border-radius:16px;padding:14px;">
         <div style="font-size:12px;color:#757D78;">${escapeHtml(c(lang, "documents"))}</div>
         <div style="font-size:22px;font-weight:700;color:#0E241A;">${documents.length}</div>
       </div>
     </div>
     <table style="width:100%;border-collapse:collapse;font-size:14px;">
       <thead>
         <tr>
           <th style="text-align:left;color:#757D78;font-weight:600;padding-bottom:8px;">${escapeHtml(c(lang, "products"))}</th>
           <th style="text-align:left;color:#757D78;font-weight:600;padding-bottom:8px;">${escapeHtml(c(lang, "merchant"))}</th>
           <th style="text-align:right;color:#757D78;font-weight:600;padding-bottom:8px;">${escapeHtml(c(lang, "price"))}</th>
         </tr>
       </thead>
       <tbody>${rows || `<tr><td colspan="3" style="color:#757D78;padding:12px 0;">—</td></tr>`}</tbody>
     </table>`
  );
}

export function shoppingListHtml(lang: MailLang, items: { name: string; qty?: string; checked?: boolean }[]) {
  const rows = (items || [])
    .map(
      (it) => `<tr>
        <td style="padding:10px 0;border-bottom:1px solid #EAE8DF;color:#202522;">${it.checked ? "☑" : "☐"} ${escapeHtml(it.name || "—")}</td>
        <td style="padding:10px 0;border-bottom:1px solid #EAE8DF;color:#757D78;text-align:right;">${escapeHtml(it.qty || "—")}</td>
      </tr>`
    )
    .join("");
  return emailShell(
    lang,
    c(lang, "shoppingT"),
    `<p style="margin:0 0 18px;color:#757D78;line-height:22px;">${escapeHtml(c(lang, "shoppingB"))}</p>
     <table style="width:100%;border-collapse:collapse;font-size:14px;">
       <thead>
         <tr>
           <th style="text-align:left;color:#757D78;font-weight:600;padding-bottom:8px;">${escapeHtml(c(lang, "item"))}</th>
           <th style="text-align:right;color:#757D78;font-weight:600;padding-bottom:8px;">${escapeHtml(c(lang, "qty"))}</th>
         </tr>
       </thead>
       <tbody>${rows || `<tr><td colspan="2" style="color:#757D78;padding:12px 0;">—</td></tr>`}</tbody>
     </table>`
  );
}

export function shoppingListText(lang: MailLang, items: { name: string; qty?: string; checked?: boolean }[]) {
  const title = c(lang, "shoppingT");
  const lines = (items || []).map((it) => `${it.checked ? "[x]" : "[ ]"} ${it.name}${it.qty ? ` (${it.qty})` : ""}`);
  return `${title}\n\n${lines.join("\n")}\n\nSaklio · Produced by aystech · Kayra Çatalkaya`;
}

export function spendingReportHtml(
  lang: MailLang,
  payload: {
    monthLabel: string;
    total: string;
    count: number;
    top?: string;
    sectors: { name: string; amount: string; share: string }[];
  }
) {
  const rows = (payload.sectors || [])
    .map(
      (s) => `<tr>
        <td style="padding:10px 0;border-bottom:1px solid #EAE8DF;color:#202522;">${escapeHtml(s.name)}</td>
        <td style="padding:10px 0;border-bottom:1px solid #EAE8DF;color:#202522;text-align:right;">${escapeHtml(s.amount)}</td>
        <td style="padding:10px 0;border-bottom:1px solid #EAE8DF;color:#757D78;text-align:right;">${escapeHtml(s.share)}</td>
      </tr>`
    )
    .join("");
  return emailShell(
    lang,
    `${c(lang, "spendT")} · ${payload.monthLabel}`,
    `<p style="margin:0 0 18px;color:#757D78;line-height:22px;">${escapeHtml(c(lang, "spendB"))}</p>
     <div style="display:flex;gap:10px;margin-bottom:18px;">
       <div style="flex:1;background:#F8F7F2;border-radius:16px;padding:14px;">
         <div style="font-size:12px;color:#757D78;">${escapeHtml(c(lang, "spendTotal"))}</div>
         <div style="font-size:22px;font-weight:700;color:#0E241A;">${escapeHtml(payload.total)}</div>
       </div>
       <div style="flex:1;background:#F8F7F2;border-radius:16px;padding:14px;">
         <div style="font-size:12px;color:#757D78;">${escapeHtml(c(lang, "spendTop"))}</div>
         <div style="font-size:16px;font-weight:700;color:#0E241A;margin-top:6px;">${escapeHtml(payload.top || "—")}</div>
       </div>
     </div>
     <table style="width:100%;border-collapse:collapse;font-size:14px;">
       <thead>
         <tr>
           <th style="text-align:left;color:#757D78;font-weight:600;padding-bottom:8px;">${escapeHtml(c(lang, "spendSector"))}</th>
           <th style="text-align:right;color:#757D78;font-weight:600;padding-bottom:8px;">${escapeHtml(c(lang, "price"))}</th>
           <th style="text-align:right;color:#757D78;font-weight:600;padding-bottom:8px;">${escapeHtml(c(lang, "spendShare"))}</th>
         </tr>
       </thead>
       <tbody>${rows || `<tr><td colspan="3" style="color:#757D78;padding:12px 0;">—</td></tr>`}</tbody>
     </table>`
  );
}

export function spendingReportText(
  lang: MailLang,
  payload: {
    monthLabel: string;
    total: string;
    top?: string;
    sectors: { name: string; amount: string; share: string }[];
  }
) {
  const lines = (payload.sectors || []).map((s) => `${s.name}: ${s.amount} (${s.share})`);
  return `${c(lang, "spendT")} · ${payload.monthLabel}\n${c(lang, "spendTotal")}: ${payload.total}\n${c(lang, "spendTop")}: ${payload.top || "—"}\n\n${lines.join("\n")}\n\nSaklio · Produced by aystech · Kayra Çatalkaya`;
}

export function downloadHtmlFile(filename: string, html: string) {
  if (typeof document === "undefined") return;
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadJsonFile(filename: string, data: unknown) {
  if (typeof document === "undefined") return;
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
